# Tabby helper config.
set -g mouse on
set -g set-clipboard on

# The helper script should be available in PATH.
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "tmux-tabby-osc52-copy #{client_tty}"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "tmux-tabby-osc52-copy #{client_tty}"
bind -T copy-mode DoubleClick1Pane select-pane \; send-keys -X select-word \; run-shell -d 0.3 \; send-keys -X copy-pipe-and-cancel "tmux-tabby-osc52-copy #{client_tty}"
bind -T copy-mode TripleClick1Pane select-pane \; send-keys -X select-line \; run-shell -d 0.3 \; send-keys -X copy-pipe-and-cancel "tmux-tabby-osc52-copy #{client_tty}"
bind -T copy-mode-vi DoubleClick1Pane select-pane \; send-keys -X select-word \; run-shell -d 0.3 \; send-keys -X copy-pipe-and-cancel "tmux-tabby-osc52-copy #{client_tty}"
bind -T copy-mode-vi TripleClick1Pane select-pane \; send-keys -X select-line \; run-shell -d 0.3 \; send-keys -X copy-pipe-and-cancel "tmux-tabby-osc52-copy #{client_tty}"
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "tmux-tabby-osc52-copy #{client_tty}"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "tmux-tabby-osc52-copy #{client_tty}"
bind -T copy-mode-vi C-j send-keys -X copy-pipe-and-cancel "tmux-tabby-osc52-copy #{client_tty}"
